# Generated by Django 6.0.7 on 2026-09-09 15:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_product_skus(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    seen = set()
    for product in Product.objects.all().iterator():
        sku = (product.sku or '').strip()
        if not sku:
            base = slugify(product.name or 'product')[:40].upper() or 'PRODUCT'
            sku = f'{base}-{uuid.uuid4().hex[:8].upper()}'
        # Guarantee uniqueness even if old or imported data carried a non-normalized SKU.
        candidate = sku
        counter = 1
        while candidate in seen:
            candidate = f'{sku}-{counter}'
            counter += 1
        seen.add(candidate)
        product.sku = candidate
        product.save(update_fields=['sku'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_default_store_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_product_skus, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_minor',
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(
                    blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='product_images', to='catalog.product')),
            ],
            options={
                'ordering': ('product', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_success', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
