# Generated by Django 6.0.7 on 2026-09-13 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='category',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('inventory', 'Inventory'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('delivery', 'Delivery'), ('account', 'Account'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('event_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
